# Generated by Django 4.0.4 on 2022-05-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10)),
                ('celphone_number', models.CharField(max_length=10)),
                ('staff', models.CharField(max_length=2, null=True)),
                ('photo', models.ImageField(blank=True, null=b'I01\n', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
