# Generated by Django 4.0.4 on 2022-05-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_users_delete_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='celphone_number',
            new_name='cell_phone_number',
        ),
    ]
