# Generated by Django 4.0.4 on 2022-05-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
