# Generated by Django 4.0.4 on 2022-05-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
