# Generated by Django 4.0.4 on 2022-05-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nturno', models.IntegerField()),
                ('hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=10)),
                ('staff', models.CharField(max_length=2, null=True)),
                ('foto', models.ImageField(blank=True, null=b'I01\n', upload_to='images/')),
            ],
        ),
    ]
