# Generated by Django 4.0.4 on 2022-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, null=b'I01\n', upload_to='images/'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='staff',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
