# Generated by Django 4.0.4 on 2022-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cedula',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
