# Generated by Django 4.0.4 on 2022-05-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_usuarios_cedula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
