# Generated by Django 4.0.4 on 2022-05-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turns', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Turnos',
        ),
    ]
