# Generated by Django 4.0.4 on 2022-05-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_turns_delete_turnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turns',
            name='Staff',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turns',
            name='user',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
