# Generated by Django 4.0.4 on 2022-05-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_alter_turns_staff_alter_turns_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turns',
            name='Staff',
            field=models.CharField(max_length=20),
        ),
    ]
